### ISSUE TITLE
Numerical issues with NaT_CML.nml channel

### ISSUE THREAD

**Issue by JustasB** [OpenSourceBrain/VervaekeEtAl-GolgiCellNetwork#1]
Hi @pgleeson,

Do you know why the nml2 version of the NaT channel would have numerical issues?

I have a simple voltage clamp protocol that runs on the order of minutes and results in a few hundred MB .dat files with many other channels. 

However, this channel+protocol combination blows up NEURON even with dts as small as 0.00001. When I modify the resulting neuron nml_.py file to run using cvode, the simulation takes hours and the resulting vectors or dat files crash 80GB ram machine or run out of disk space.

Any ideas what might be happening with this channel?

The attached zip contains a self-contained LEMS file with the protocol (+channel), and can be run with jnml -neuron

[LEMS.zip](https://github.com/OpenSourceBrain/VervaekeEtAl-GolgiCellNetwork/files/1451736/LEMS.zip)

**Comment by pgleeson** [comment]
Have a look here: https://github.com/OpenSourceBrain/VervaekeEtAl-GolgiCellNetwork/blob/master/NeuroML2/analyse_chans.sh

The channel is not v well constructed in that the tau goes to nearly zero. See https://github.com/OpenSourceBrain/VervaekeEtAl-GolgiCellNetwork/blob/master/NeuroML2/channel_summary/README.md. The numeric integration fails with such a small tau in the time deriv statement

If you can somehow limit your protocol to min -75mV that might help...

**Comment by scrook** [comment]
Change protocol slightly and add detailed note about problem with Tau.

**Comment by JustasB** [comment]
> If you can somehow limit your protocol to min -75mV that might help...

That's what I ended up doing with this channel. Thanks for the tip, Padraig.
